// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Model struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	ModelID     string             `db:"model_id" json:"model_id"`
	DisplayName *string            `db:"display_name" json:"display_name"`
	Active      bool               `db:"active" json:"active"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Workspace struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	Slug             string             `db:"slug" json:"slug"`
	Name             string             `db:"name" json:"name"`
	ManagementRepoID string             `db:"management_repo_id" json:"management_repo_id"`
	BranchPattern    *string            `db:"branch_pattern" json:"branch_pattern"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SlackChannelID   *string            `db:"slack_channel_id" json:"slack_channel_id"`
	OrganizationID   pgtype.UUID        `db:"organization_id" json:"organization_id"`
}

type WorkspaceActivityEvent struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ScopeType   string             `db:"scope_type" json:"scope_type"`
	Action      *string            `db:"action" json:"action"`
	Actor       *string            `db:"actor" json:"actor"`
	OccurredAt  *string            `db:"occurred_at" json:"occurred_at"`
	Note        *string            `db:"note" json:"note"`
	Sequence    int32              `db:"sequence" json:"sequence"`
	RawEvent    json.RawMessage    `db:"raw_event" json:"raw_event"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	FeatureName *string            `db:"feature_name" json:"feature_name"`
	TaskName    *string            `db:"task_name" json:"task_name"`
	FeatureID   pgtype.UUID        `db:"feature_id" json:"feature_id"`
	TaskID      pgtype.UUID        `db:"task_id" json:"task_id"`
	ActorID     *string            `db:"actor_id" json:"actor_id"`
	Enriched    bool               `db:"enriched" json:"enriched"`
}

type WorkspaceFeature struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID   pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	Title         string             `db:"title" json:"title"`
	FeatureStatus *string            `db:"feature_status" json:"feature_status"`
	CurrentStage  *string            `db:"current_stage" json:"current_stage"`
	NextAction    *string            `db:"next_action" json:"next_action"`
	Stages        []byte             `db:"stages" json:"stages"`
	SourcePath    *string            `db:"source_path" json:"source_path"`
	SourceHash    *string            `db:"source_hash" json:"source_hash"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	FeatureName   string             `db:"feature_name" json:"feature_name"`
	FeatureID     pgtype.UUID        `db:"feature_id" json:"feature_id"`
	Owner         *string            `db:"owner" json:"owner"`
	InitPrUrl     *string            `db:"init_pr_url" json:"init_pr_url"`
	InitPrMerged  bool               `db:"init_pr_merged" json:"init_pr_merged"`
}

type WorkspaceFeatureDocument struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID  pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	DocumentType string             `db:"document_type" json:"document_type"`
	SourcePath   string             `db:"source_path" json:"source_path"`
	Url          *string            `db:"url" json:"url"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	FeatureName  string             `db:"feature_name" json:"feature_name"`
	FeatureID    pgtype.UUID        `db:"feature_id" json:"feature_id"`
}

type WorkspaceFeatureHandoff struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID    pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	FeatureID      pgtype.UUID        `db:"feature_id" json:"feature_id"`
	MgmtPrUrl      *string            `db:"mgmt_pr_url" json:"mgmt_pr_url"`
	Status         string             `db:"status" json:"status"`
	CreateAttempts int32              `db:"create_attempts" json:"create_attempts"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	FinalizedAt    pgtype.Timestamptz `db:"finalized_at" json:"finalized_at"`
}

type WorkspaceFeatureHandoffPr struct {
	ID                         pgtype.UUID        `db:"id" json:"id"`
	HandoffID                  pgtype.UUID        `db:"handoff_id" json:"handoff_id"`
	Repo                       string             `db:"repo" json:"repo"`
	PrUrl                      *string            `db:"pr_url" json:"pr_url"`
	Status                     string             `db:"status" json:"status"`
	ConflictState              string             `db:"conflict_state" json:"conflict_state"`
	ConflictResolutionAttempts int32              `db:"conflict_resolution_attempts" json:"conflict_resolution_attempts"`
	DispatchHandle             *string            `db:"dispatch_handle" json:"dispatch_handle"`
	DispatchNonce              *string            `db:"dispatch_nonce" json:"dispatch_nonce"`
	DispatchedAt               pgtype.Timestamptz `db:"dispatched_at" json:"dispatched_at"`
	ReenqueueAttempts          int32              `db:"reenqueue_attempts" json:"reenqueue_attempts"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WorkspaceGithubSource struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID   pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	RepoUrl       string             `db:"repo_url" json:"repo_url"`
	RepoOwner     string             `db:"repo_owner" json:"repo_owner"`
	RepoName      string             `db:"repo_name" json:"repo_name"`
	DefaultBranch *string            `db:"default_branch" json:"default_branch"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WorkspaceModelPolicy struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	Phase       string             `db:"phase" json:"phase"`
	ModelID     pgtype.UUID        `db:"model_id" json:"model_id"`
	IsDefault   bool               `db:"is_default" json:"is_default"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WorkspaceRepo struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	RepoID      string             `db:"repo_id" json:"repo_id"`
	BaseBranch  *string            `db:"base_branch" json:"base_branch"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RepoUrl     *string            `db:"repo_url" json:"repo_url"`
}

type WorkspaceSyncRun struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID  pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	Trigger      string             `db:"trigger" json:"trigger"`
	Branch       *string            `db:"branch" json:"branch"`
	Mode         string             `db:"mode" json:"mode"`
	Status       string             `db:"status" json:"status"`
	CommitSha    *string            `db:"commit_sha" json:"commit_sha"`
	ChangedPaths []byte             `db:"changed_paths" json:"changed_paths"`
	StartedAt    pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt   pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	ErrorCode    *string            `db:"error_code" json:"error_code"`
	ErrorMessage *string            `db:"error_message" json:"error_message"`
	Metadata     []byte             `db:"metadata" json:"metadata"`
	FeatureID    pgtype.UUID        `db:"feature_id" json:"feature_id"`
	TaskID       pgtype.UUID        `db:"task_id" json:"task_id"`
}

type WorkspaceTask struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID           pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	Title                 string             `db:"title" json:"title"`
	Repo                  *string            `db:"repo" json:"repo"`
	Status                *string            `db:"status" json:"status"`
	DependsOn             json.RawMessage    `db:"depends_on" json:"depends_on"`
	BlockedReason         *string            `db:"blocked_reason" json:"blocked_reason"`
	Branch                *string            `db:"branch" json:"branch"`
	Execution             []byte             `db:"execution" json:"execution"`
	Pr                    []byte             `db:"pr" json:"pr"`
	WorkspacePr           []byte             `db:"workspace_pr" json:"workspace_pr"`
	SourcePath            *string            `db:"source_path" json:"source_path"`
	SourceHash            *string            `db:"source_hash" json:"source_hash"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	FeatureName           string             `db:"feature_name" json:"feature_name"`
	FeatureID             pgtype.UUID        `db:"feature_id" json:"feature_id"`
	TaskName              string             `db:"task_name" json:"task_name"`
	TaskID                pgtype.UUID        `db:"task_id" json:"task_id"`
	Owner                 *string            `db:"owner" json:"owner"`
	DispatchHandle        *string            `db:"dispatch_handle" json:"dispatch_handle"`
	DispatchNonce         *string            `db:"dispatch_nonce" json:"dispatch_nonce"`
	DispatchedAt          pgtype.Timestamptz `db:"dispatched_at" json:"dispatched_at"`
	ReenqueueAttempts     int32              `db:"reenqueue_attempts" json:"reenqueue_attempts"`
	ReviewIncompleteCount int32              `db:"review_incomplete_count" json:"review_incomplete_count"`
	MaxTurnsRetryCount    int32              `db:"max_turns_retry_count" json:"max_turns_retry_count"`
	RebaseAttempts        int32              `db:"rebase_attempts" json:"rebase_attempts"`
	ConflictState         string             `db:"conflict_state" json:"conflict_state"`
	DispatchKind          *string            `db:"dispatch_kind" json:"dispatch_kind"`
	BlockedFromStatus     *string            `db:"blocked_from_status" json:"blocked_from_status"`
	BlockedDetails        *string            `db:"blocked_details" json:"blocked_details"`
}
