// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const listWorkspaceFeatures = `-- name: ListWorkspaceFeatures :many
SELECT id, workspace_id, feature_id, feature_name, title, feature_status, current_stage, next_action,
       stages, source_path, source_hash, created_at, updated_at
FROM workspace_features
WHERE workspace_id = $1
ORDER BY updated_at DESC`

func (q *Queries) ListWorkspaceFeatures(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceFeature, error) {
	rows, err := q.db.Query(ctx, listWorkspaceFeatures, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceFeature
	for rows.Next() {
		var i WorkspaceFeature
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FeatureID,
			&i.FeatureName,
			&i.Title,
			&i.FeatureStatus,
			&i.CurrentStage,
			&i.NextAction,
			&i.Stages,
			&i.SourcePath,
			&i.SourceHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceFeature = `-- name: GetWorkspaceFeature :one
SELECT id, workspace_id, feature_id, feature_name, title, feature_status, current_stage, next_action,
       stages, source_path, source_hash, created_at, updated_at
FROM workspace_features
WHERE workspace_id = $1 AND feature_id = $2`

type GetWorkspaceFeatureParams struct {
	WorkspaceID pgtype.UUID
	FeatureID   pgtype.UUID
}

func (q *Queries) GetWorkspaceFeature(ctx context.Context, arg GetWorkspaceFeatureParams) (WorkspaceFeature, error) {
	row := q.db.QueryRow(ctx, getWorkspaceFeature, arg.WorkspaceID, arg.FeatureID)
	var i WorkspaceFeature
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FeatureID,
		&i.FeatureName,
		&i.Title,
		&i.FeatureStatus,
		&i.CurrentStage,
		&i.NextAction,
		&i.Stages,
		&i.SourcePath,
		&i.SourceHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkspaceFeature = `-- name: UpsertWorkspaceFeature :one
WITH feature_input AS (
    SELECT COALESCE(
        (SELECT id FROM workspace_features WHERE workspace_id = $1 AND feature_name = $2),
        gen_random_uuid()
    ) AS feature_uuid
)
INSERT INTO workspace_features (
    id, workspace_id, feature_id, feature_name, title, feature_status, current_stage, next_action,
    stages, source_path, source_hash, created_at, updated_at
)
SELECT feature_uuid, $1, feature_uuid, $2, $3, $4, $5, $6, $7, $8, $9, now(), now()
FROM feature_input
ON CONFLICT (workspace_id, feature_name) DO UPDATE SET
    title          = EXCLUDED.title,
    feature_status = EXCLUDED.feature_status,
    current_stage  = EXCLUDED.current_stage,
    next_action    = EXCLUDED.next_action,
    stages         = EXCLUDED.stages,
    source_path    = EXCLUDED.source_path,
    source_hash    = EXCLUDED.source_hash,
    updated_at     = now()
RETURNING id, workspace_id, feature_id, feature_name, title, feature_status, current_stage, next_action,
          stages, source_path, source_hash, created_at, updated_at`

type UpsertWorkspaceFeatureParams struct {
	WorkspaceID   pgtype.UUID
	FeatureName   string
	Title         string
	FeatureStatus *string
	CurrentStage  *string
	NextAction    *string
	Stages        json.RawMessage
	SourcePath    string
	SourceHash    *string
}

func (q *Queries) UpsertWorkspaceFeature(ctx context.Context, arg UpsertWorkspaceFeatureParams) (WorkspaceFeature, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceFeature,
		arg.WorkspaceID,
		arg.FeatureName,
		arg.Title,
		arg.FeatureStatus,
		arg.CurrentStage,
		arg.NextAction,
		arg.Stages,
		arg.SourcePath,
		arg.SourceHash,
	)
	var i WorkspaceFeature
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FeatureID,
		&i.FeatureName,
		&i.Title,
		&i.FeatureStatus,
		&i.CurrentStage,
		&i.NextAction,
		&i.Stages,
		&i.SourcePath,
		&i.SourceHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspaceFeaturesNotIn = `-- name: DeleteWorkspaceFeaturesNotIn :exec
DELETE FROM workspace_features
WHERE workspace_id = $1
  AND feature_name != ALL($2::text[])`

type DeleteWorkspaceFeaturesNotInParams struct {
	WorkspaceID  pgtype.UUID
	FeatureNames []string
}

func (q *Queries) DeleteWorkspaceFeaturesNotIn(ctx context.Context, arg DeleteWorkspaceFeaturesNotInParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceFeaturesNotIn, arg.WorkspaceID, arg.FeatureNames)
	return err
}
