// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listWorkspaceRepos = `-- name: ListWorkspaceRepos :many
SELECT id, workspace_id, repo_id, base_branch, created_at, updated_at
FROM workspace_repos
WHERE workspace_id = $1
ORDER BY repo_id`

func (q *Queries) ListWorkspaceRepos(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceRepo, error) {
	rows, err := q.db.Query(ctx, listWorkspaceRepos, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceRepo
	for rows.Next() {
		var i WorkspaceRepo
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RepoID,
			&i.BaseBranch,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkspaceRepo = `-- name: UpsertWorkspaceRepo :one
INSERT INTO workspace_repos (workspace_id, repo_id, base_branch, created_at, updated_at)
VALUES ($1, $2, $3, now(), now())
ON CONFLICT (workspace_id, repo_id) DO UPDATE SET
    base_branch = EXCLUDED.base_branch,
    updated_at  = now()
RETURNING id, workspace_id, repo_id, base_branch, created_at, updated_at`

type UpsertWorkspaceRepoParams struct {
	WorkspaceID pgtype.UUID
	RepoID      string
	BaseBranch  *string
}

func (q *Queries) UpsertWorkspaceRepo(ctx context.Context, arg UpsertWorkspaceRepoParams) (WorkspaceRepo, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceRepo,
		arg.WorkspaceID,
		arg.RepoID,
		arg.BaseBranch,
	)
	var i WorkspaceRepo
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepoID,
		&i.BaseBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspaceReposNotIn = `-- name: DeleteWorkspaceReposNotIn :exec
DELETE FROM workspace_repos
WHERE workspace_id = $1
  AND repo_id != ALL($2::text[])`

type DeleteWorkspaceReposNotInParams struct {
	WorkspaceID pgtype.UUID
	RepoIds     []string
}

func (q *Queries) DeleteWorkspaceReposNotIn(ctx context.Context, arg DeleteWorkspaceReposNotInParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceReposNotIn, arg.WorkspaceID, arg.RepoIds)
	return err
}
