// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_github_sources.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGitHubSource = `-- name: GetGitHubSource :one
SELECT id, workspace_id, repo_url, repo_owner, repo_name, default_branch, created_at, updated_at
FROM workspace_github_sources
WHERE workspace_id = $1
`

func (q *Queries) GetGitHubSource(ctx context.Context, workspaceID pgtype.UUID) (WorkspaceGithubSource, error) {
	row := q.db.QueryRow(ctx, getGitHubSource, workspaceID)
	var i WorkspaceGithubSource
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepoUrl,
		&i.RepoOwner,
		&i.RepoName,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGitHubSource = `-- name: UpsertGitHubSource :one
INSERT INTO workspace_github_sources (
    workspace_id, repo_url, repo_owner, repo_name, default_branch, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, now(), now())
ON CONFLICT (workspace_id) DO UPDATE SET
    repo_url       = EXCLUDED.repo_url,
    repo_owner     = EXCLUDED.repo_owner,
    repo_name      = EXCLUDED.repo_name,
    default_branch = EXCLUDED.default_branch,
    updated_at     = now()
RETURNING id, workspace_id, repo_url, repo_owner, repo_name, default_branch, created_at, updated_at
`

type UpsertGitHubSourceParams struct {
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	RepoUrl       string      `db:"repo_url" json:"repo_url"`
	RepoOwner     string      `db:"repo_owner" json:"repo_owner"`
	RepoName      string      `db:"repo_name" json:"repo_name"`
	DefaultBranch *string     `db:"default_branch" json:"default_branch"`
}

func (q *Queries) UpsertGitHubSource(ctx context.Context, arg UpsertGitHubSourceParams) (WorkspaceGithubSource, error) {
	row := q.db.QueryRow(ctx, upsertGitHubSource,
		arg.WorkspaceID,
		arg.RepoUrl,
		arg.RepoOwner,
		arg.RepoName,
		arg.DefaultBranch,
	)
	var i WorkspaceGithubSource
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepoUrl,
		&i.RepoOwner,
		&i.RepoName,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
