// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_activity_events.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllFeatureActivityEvents = `-- name: DeleteAllFeatureActivityEvents :exec
DELETE FROM workspace_activity_events
WHERE workspace_id = $1 AND feature_id = $2
`

type DeleteAllFeatureActivityEventsParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	FeatureID   pgtype.UUID `db:"feature_id" json:"feature_id"`
}

func (q *Queries) DeleteAllFeatureActivityEvents(ctx context.Context, arg DeleteAllFeatureActivityEventsParams) error {
	_, err := q.db.Exec(ctx, deleteAllFeatureActivityEvents, arg.WorkspaceID, arg.FeatureID)
	return err
}

const listActivityEvents = `-- name: ListActivityEvents :many
SELECT id, workspace_id, scope_type, action, actor,
       occurred_at, note, sequence, raw_event, created_at, feature_name, task_name, feature_id, task_id
FROM workspace_activity_events
WHERE workspace_id = $1
ORDER BY occurred_at DESC, sequence DESC
`

func (q *Queries) ListActivityEvents(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceActivityEvent, error) {
	rows, err := q.db.Query(ctx, listActivityEvents, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceActivityEvent{}
	for rows.Next() {
		var i WorkspaceActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ScopeType,
			&i.Action,
			&i.Actor,
			&i.OccurredAt,
			&i.Note,
			&i.Sequence,
			&i.RawEvent,
			&i.CreatedAt,
			&i.FeatureName,
			&i.TaskName,
			&i.FeatureID,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureActivityEvents = `-- name: ListFeatureActivityEvents :many
SELECT id, workspace_id, scope_type, action, actor,
       occurred_at, note, sequence, raw_event, created_at, feature_name, task_name, feature_id, task_id
FROM workspace_activity_events
WHERE workspace_id = $1 AND feature_id = $2
ORDER BY occurred_at DESC, sequence DESC
`

type ListFeatureActivityEventsParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	FeatureID   pgtype.UUID `db:"feature_id" json:"feature_id"`
}

func (q *Queries) ListFeatureActivityEvents(ctx context.Context, arg ListFeatureActivityEventsParams) ([]WorkspaceActivityEvent, error) {
	rows, err := q.db.Query(ctx, listFeatureActivityEvents, arg.WorkspaceID, arg.FeatureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceActivityEvent{}
	for rows.Next() {
		var i WorkspaceActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ScopeType,
			&i.Action,
			&i.Actor,
			&i.OccurredAt,
			&i.Note,
			&i.Sequence,
			&i.RawEvent,
			&i.CreatedAt,
			&i.FeatureName,
			&i.TaskName,
			&i.FeatureID,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskActivityEvents = `-- name: ListTaskActivityEvents :many
SELECT id, workspace_id, scope_type, action, actor,
       occurred_at, note, sequence, raw_event, created_at, feature_name, task_name, feature_id, task_id
FROM workspace_activity_events
WHERE workspace_id = $1 AND feature_id = $2 AND task_id = $3
ORDER BY sequence
`

type ListTaskActivityEventsParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	FeatureID   pgtype.UUID `db:"feature_id" json:"feature_id"`
	TaskID      pgtype.UUID `db:"task_id" json:"task_id"`
}

func (q *Queries) ListTaskActivityEvents(ctx context.Context, arg ListTaskActivityEventsParams) ([]WorkspaceActivityEvent, error) {
	rows, err := q.db.Query(ctx, listTaskActivityEvents, arg.WorkspaceID, arg.FeatureID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceActivityEvent{}
	for rows.Next() {
		var i WorkspaceActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ScopeType,
			&i.Action,
			&i.Actor,
			&i.OccurredAt,
			&i.Note,
			&i.Sequence,
			&i.RawEvent,
			&i.CreatedAt,
			&i.FeatureName,
			&i.TaskName,
			&i.FeatureID,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeatureActivityEvent = `-- name: UpsertFeatureActivityEvent :one
INSERT INTO workspace_activity_events (
    workspace_id, scope_type, feature_id, feature_name, task_id, action, actor,
    occurred_at, note, sequence, raw_event, created_at
)
VALUES ($1, $2, $3, $4, NULL, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (workspace_id, feature_id, sequence)
    WHERE feature_id IS NOT NULL AND task_id IS NULL
DO UPDATE SET
    scope_type   = EXCLUDED.scope_type,
    feature_name = EXCLUDED.feature_name,
    action       = EXCLUDED.action,
    actor        = EXCLUDED.actor,
    occurred_at  = EXCLUDED.occurred_at,
    note         = EXCLUDED.note,
    raw_event    = EXCLUDED.raw_event
RETURNING id, workspace_id, scope_type, action, actor,
          occurred_at, note, sequence, raw_event, created_at, feature_name, task_name, feature_id, task_id
`

type UpsertFeatureActivityEventParams struct {
	WorkspaceID pgtype.UUID     `db:"workspace_id" json:"workspace_id"`
	ScopeType   string          `db:"scope_type" json:"scope_type"`
	FeatureID   pgtype.UUID     `db:"feature_id" json:"feature_id"`
	FeatureName *string         `db:"feature_name" json:"feature_name"`
	Action      *string         `db:"action" json:"action"`
	Actor       *string         `db:"actor" json:"actor"`
	OccurredAt  *string         `db:"occurred_at" json:"occurred_at"`
	Note        *string         `db:"note" json:"note"`
	Sequence    int32           `db:"sequence" json:"sequence"`
	RawEvent    json.RawMessage `db:"raw_event" json:"raw_event"`
}

// Targets the partial index: feature_id IS NOT NULL AND task_id IS NULL.
func (q *Queries) UpsertFeatureActivityEvent(ctx context.Context, arg UpsertFeatureActivityEventParams) (WorkspaceActivityEvent, error) {
	row := q.db.QueryRow(ctx, upsertFeatureActivityEvent,
		arg.WorkspaceID,
		arg.ScopeType,
		arg.FeatureID,
		arg.FeatureName,
		arg.Action,
		arg.Actor,
		arg.OccurredAt,
		arg.Note,
		arg.Sequence,
		arg.RawEvent,
	)
	var i WorkspaceActivityEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.Action,
		&i.Actor,
		&i.OccurredAt,
		&i.Note,
		&i.Sequence,
		&i.RawEvent,
		&i.CreatedAt,
		&i.FeatureName,
		&i.TaskName,
		&i.FeatureID,
		&i.TaskID,
	)
	return i, err
}

const upsertTaskActivityEvent = `-- name: UpsertTaskActivityEvent :one
INSERT INTO workspace_activity_events (
    workspace_id, scope_type, feature_id, feature_name, task_id, task_name, action, actor,
    occurred_at, note, sequence, raw_event, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now())
ON CONFLICT (workspace_id, feature_id, task_id, sequence)
    WHERE feature_id IS NOT NULL AND task_id IS NOT NULL
DO UPDATE SET
    scope_type   = EXCLUDED.scope_type,
    feature_name = EXCLUDED.feature_name,
    task_name    = EXCLUDED.task_name,
    action       = EXCLUDED.action,
    actor        = EXCLUDED.actor,
    occurred_at  = EXCLUDED.occurred_at,
    note         = EXCLUDED.note,
    raw_event    = EXCLUDED.raw_event
RETURNING id, workspace_id, scope_type, action, actor,
          occurred_at, note, sequence, raw_event, created_at, feature_name, task_name, feature_id, task_id
`

type UpsertTaskActivityEventParams struct {
	WorkspaceID pgtype.UUID     `db:"workspace_id" json:"workspace_id"`
	ScopeType   string          `db:"scope_type" json:"scope_type"`
	FeatureID   pgtype.UUID     `db:"feature_id" json:"feature_id"`
	FeatureName *string         `db:"feature_name" json:"feature_name"`
	TaskID      pgtype.UUID     `db:"task_id" json:"task_id"`
	TaskName    *string         `db:"task_name" json:"task_name"`
	Action      *string         `db:"action" json:"action"`
	Actor       *string         `db:"actor" json:"actor"`
	OccurredAt  *string         `db:"occurred_at" json:"occurred_at"`
	Note        *string         `db:"note" json:"note"`
	Sequence    int32           `db:"sequence" json:"sequence"`
	RawEvent    json.RawMessage `db:"raw_event" json:"raw_event"`
}

// Targets the partial index: feature_id IS NOT NULL AND task_id IS NOT NULL.
func (q *Queries) UpsertTaskActivityEvent(ctx context.Context, arg UpsertTaskActivityEventParams) (WorkspaceActivityEvent, error) {
	row := q.db.QueryRow(ctx, upsertTaskActivityEvent,
		arg.WorkspaceID,
		arg.ScopeType,
		arg.FeatureID,
		arg.FeatureName,
		arg.TaskID,
		arg.TaskName,
		arg.Action,
		arg.Actor,
		arg.OccurredAt,
		arg.Note,
		arg.Sequence,
		arg.RawEvent,
	)
	var i WorkspaceActivityEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.Action,
		&i.Actor,
		&i.OccurredAt,
		&i.Note,
		&i.Sequence,
		&i.RawEvent,
		&i.CreatedAt,
		&i.FeatureName,
		&i.TaskName,
		&i.FeatureID,
		&i.TaskID,
	)
	return i, err
}
