// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const listFeatureTasks = `-- name: ListFeatureTasks :many
SELECT id, workspace_id, feature_id, feature_name, task_id, title, repo, status, depends_on,
       blocked_reason, branch, execution, pr, workspace_pr, source_path, source_hash,
       created_at, updated_at
FROM workspace_tasks
WHERE workspace_id = $1 AND feature_name = $2
ORDER BY task_id`

type ListFeatureTasksParams struct {
	WorkspaceID pgtype.UUID
	FeatureID   string
}

func (q *Queries) ListFeatureTasks(ctx context.Context, arg ListFeatureTasksParams) ([]WorkspaceTask, error) {
	rows, err := q.db.Query(ctx, listFeatureTasks, arg.WorkspaceID, arg.FeatureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceTask
	for rows.Next() {
		var i WorkspaceTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FeatureID,
			&i.FeatureName,
			&i.TaskID,
			&i.Title,
			&i.Repo,
			&i.Status,
			&i.DependsOn,
			&i.BlockedReason,
			&i.Branch,
			&i.Execution,
			&i.Pr,
			&i.WorkspacePr,
			&i.SourcePath,
			&i.SourceHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceTasks = `-- name: ListWorkspaceTasks :many
SELECT id, workspace_id, feature_id, feature_name, task_id, title, repo, status, depends_on,
       blocked_reason, branch, execution, pr, workspace_pr, source_path, source_hash,
       created_at, updated_at
FROM workspace_tasks
WHERE workspace_id = $1
ORDER BY feature_name, task_id`

func (q *Queries) ListWorkspaceTasks(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceTask, error) {
	rows, err := q.db.Query(ctx, listWorkspaceTasks, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceTask
	for rows.Next() {
		var i WorkspaceTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FeatureID,
			&i.FeatureName,
			&i.TaskID,
			&i.Title,
			&i.Repo,
			&i.Status,
			&i.DependsOn,
			&i.BlockedReason,
			&i.Branch,
			&i.Execution,
			&i.Pr,
			&i.WorkspacePr,
			&i.SourcePath,
			&i.SourceHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceTask = `-- name: GetWorkspaceTask :one
SELECT id, workspace_id, feature_id, feature_name, task_id, title, repo, status, depends_on,
       blocked_reason, branch, execution, pr, workspace_pr, source_path, source_hash,
       created_at, updated_at
FROM workspace_tasks
WHERE workspace_id = $1 AND feature_name = $2 AND task_id = $3`

type GetWorkspaceTaskParams struct {
	WorkspaceID pgtype.UUID
	FeatureID   string
	TaskID      string
}

func (q *Queries) GetWorkspaceTask(ctx context.Context, arg GetWorkspaceTaskParams) (WorkspaceTask, error) {
	row := q.db.QueryRow(ctx, getWorkspaceTask, arg.WorkspaceID, arg.FeatureID, arg.TaskID)
	var i WorkspaceTask
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FeatureID,
		&i.FeatureName,
		&i.TaskID,
		&i.Title,
		&i.Repo,
		&i.Status,
		&i.DependsOn,
		&i.BlockedReason,
		&i.Branch,
		&i.Execution,
		&i.Pr,
		&i.WorkspacePr,
		&i.SourcePath,
		&i.SourceHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkspaceTask = `-- name: UpsertWorkspaceTask :one
INSERT INTO workspace_tasks (
    workspace_id, feature_id, feature_name, task_id, title, repo, status, depends_on,
    blocked_reason, branch, execution, pr, workspace_pr, source_path, source_hash,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, now(), now())
ON CONFLICT (workspace_id, feature_id, task_id) DO UPDATE SET
    feature_name   = EXCLUDED.feature_name,
    title          = EXCLUDED.title,
    repo           = EXCLUDED.repo,
    status         = EXCLUDED.status,
    depends_on     = EXCLUDED.depends_on,
    blocked_reason = EXCLUDED.blocked_reason,
    branch         = EXCLUDED.branch,
    execution      = EXCLUDED.execution,
    pr             = EXCLUDED.pr,
    workspace_pr   = EXCLUDED.workspace_pr,
    source_path    = EXCLUDED.source_path,
    source_hash    = EXCLUDED.source_hash,
    updated_at     = now()
RETURNING id, workspace_id, feature_id, feature_name, task_id, title, repo, status, depends_on,
          blocked_reason, branch, execution, pr, workspace_pr, source_path, source_hash,
          created_at, updated_at`

type UpsertWorkspaceTaskParams struct {
	WorkspaceID   pgtype.UUID
	FeatureID     pgtype.UUID
	FeatureName   string
	TaskID        string
	Title         string
	Repo          *string
	Status        *string
	DependsOn     json.RawMessage
	BlockedReason *string
	Branch        *string
	Execution     json.RawMessage
	Pr            json.RawMessage
	WorkspacePr   json.RawMessage
	SourcePath    string
	SourceHash    *string
}

func (q *Queries) UpsertWorkspaceTask(ctx context.Context, arg UpsertWorkspaceTaskParams) (WorkspaceTask, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceTask,
		arg.WorkspaceID,
		arg.FeatureID,
		arg.FeatureName,
		arg.TaskID,
		arg.Title,
		arg.Repo,
		arg.Status,
		arg.DependsOn,
		arg.BlockedReason,
		arg.Branch,
		arg.Execution,
		arg.Pr,
		arg.WorkspacePr,
		arg.SourcePath,
		arg.SourceHash,
	)
	var i WorkspaceTask
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FeatureID,
		&i.FeatureName,
		&i.TaskID,
		&i.Title,
		&i.Repo,
		&i.Status,
		&i.DependsOn,
		&i.BlockedReason,
		&i.Branch,
		&i.Execution,
		&i.Pr,
		&i.WorkspacePr,
		&i.SourcePath,
		&i.SourceHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFeatureTasksNotIn = `-- name: DeleteFeatureTasksNotIn :exec
DELETE FROM workspace_tasks
WHERE workspace_id = $1
  AND feature_id = $2
  AND task_id != ALL($3::text[])`

type DeleteFeatureTasksNotInParams struct {
	WorkspaceID pgtype.UUID
	FeatureID   pgtype.UUID
	TaskIds     []string
}

func (q *Queries) DeleteFeatureTasksNotIn(ctx context.Context, arg DeleteFeatureTasksNotInParams) error {
	_, err := q.db.Exec(ctx, deleteFeatureTasksNotIn, arg.WorkspaceID, arg.FeatureID, arg.TaskIds)
	return err
}

const deleteAllFeatureTasks = `-- name: DeleteAllFeatureTasks :exec
DELETE FROM workspace_tasks
WHERE workspace_id = $1 AND feature_id = $2`

type DeleteAllFeatureTasksParams struct {
	WorkspaceID pgtype.UUID
	FeatureID   pgtype.UUID
}

func (q *Queries) DeleteAllFeatureTasks(ctx context.Context, arg DeleteAllFeatureTasksParams) error {
	_, err := q.db.Exec(ctx, deleteAllFeatureTasks, arg.WorkspaceID, arg.FeatureID)
	return err
}
