// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_feature_documents.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllFeatureDocuments = `-- name: DeleteAllFeatureDocuments :exec
DELETE FROM workspace_feature_documents
WHERE workspace_id = $1 AND feature_id = $2
`

type DeleteAllFeatureDocumentsParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	FeatureID   pgtype.UUID `db:"feature_id" json:"feature_id"`
}

func (q *Queries) DeleteAllFeatureDocuments(ctx context.Context, arg DeleteAllFeatureDocumentsParams) error {
	_, err := q.db.Exec(ctx, deleteAllFeatureDocuments, arg.WorkspaceID, arg.FeatureID)
	return err
}

const deleteFeatureDocumentsNotIn = `-- name: DeleteFeatureDocumentsNotIn :exec
DELETE FROM workspace_feature_documents
WHERE workspace_id = $1
  AND feature_id = $2
  AND document_type != ALL($3::text[])
`

type DeleteFeatureDocumentsNotInParams struct {
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	FeatureID     pgtype.UUID `db:"feature_id" json:"feature_id"`
	DocumentTypes []string    `db:"document_types" json:"document_types"`
}

func (q *Queries) DeleteFeatureDocumentsNotIn(ctx context.Context, arg DeleteFeatureDocumentsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteFeatureDocumentsNotIn, arg.WorkspaceID, arg.FeatureID, arg.DocumentTypes)
	return err
}

const listFeatureDocuments = `-- name: ListFeatureDocuments :many
SELECT id, workspace_id, document_type, source_path, url, created_at, updated_at, feature_name, feature_id
FROM workspace_feature_documents
WHERE workspace_id = $1 AND feature_id = $2
ORDER BY document_type
`

type ListFeatureDocumentsParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	FeatureID   pgtype.UUID `db:"feature_id" json:"feature_id"`
}

func (q *Queries) ListFeatureDocuments(ctx context.Context, arg ListFeatureDocumentsParams) ([]WorkspaceFeatureDocument, error) {
	rows, err := q.db.Query(ctx, listFeatureDocuments, arg.WorkspaceID, arg.FeatureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceFeatureDocument{}
	for rows.Next() {
		var i WorkspaceFeatureDocument
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DocumentType,
			&i.SourcePath,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeatureName,
			&i.FeatureID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceFeatureDocuments = `-- name: ListWorkspaceFeatureDocuments :many
SELECT id, workspace_id, document_type, source_path, url, created_at, updated_at, feature_name, feature_id
FROM workspace_feature_documents
WHERE workspace_id = $1
ORDER BY feature_name, document_type
`

func (q *Queries) ListWorkspaceFeatureDocuments(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceFeatureDocument, error) {
	rows, err := q.db.Query(ctx, listWorkspaceFeatureDocuments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceFeatureDocument{}
	for rows.Next() {
		var i WorkspaceFeatureDocument
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DocumentType,
			&i.SourcePath,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeatureName,
			&i.FeatureID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeatureDocument = `-- name: UpsertFeatureDocument :one
INSERT INTO workspace_feature_documents (
    workspace_id, feature_id, feature_name, document_type, source_path, url, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, now(), now())
ON CONFLICT (workspace_id, feature_id, document_type) DO UPDATE SET
    feature_name  = EXCLUDED.feature_name,
    source_path   = EXCLUDED.source_path,
    url           = EXCLUDED.url,
    updated_at    = now()
RETURNING id, workspace_id, document_type, source_path, url, created_at, updated_at, feature_name, feature_id
`

type UpsertFeatureDocumentParams struct {
	WorkspaceID  pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	FeatureID    pgtype.UUID `db:"feature_id" json:"feature_id"`
	FeatureName  string      `db:"feature_name" json:"feature_name"`
	DocumentType string      `db:"document_type" json:"document_type"`
	SourcePath   string      `db:"source_path" json:"source_path"`
	Url          *string     `db:"url" json:"url"`
}

func (q *Queries) UpsertFeatureDocument(ctx context.Context, arg UpsertFeatureDocumentParams) (WorkspaceFeatureDocument, error) {
	row := q.db.QueryRow(ctx, upsertFeatureDocument,
		arg.WorkspaceID,
		arg.FeatureID,
		arg.FeatureName,
		arg.DocumentType,
		arg.SourcePath,
		arg.Url,
	)
	var i WorkspaceFeatureDocument
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DocumentType,
		&i.SourcePath,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeatureName,
		&i.FeatureID,
	)
	return i, err
}
