// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_model_policies.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWorkspaceModelPolicies = `-- name: DeleteWorkspaceModelPolicies :exec
DELETE FROM workspace_model_policies WHERE workspace_id = $1
`

func (q *Queries) DeleteWorkspaceModelPolicies(ctx context.Context, workspaceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceModelPolicies, workspaceID)
	return err
}

const getModelByModelID = `-- name: GetModelByModelID :one
SELECT id, model_id, display_name, active, created_at, updated_at
FROM models
WHERE model_id = $1
`

func (q *Queries) GetModelByModelID(ctx context.Context, modelID string) (Model, error) {
	row := q.db.QueryRow(ctx, getModelByModelID, modelID)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.DisplayName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkspaceModelPolicy = `-- name: InsertWorkspaceModelPolicy :exec
INSERT INTO workspace_model_policies (workspace_id, phase, model_id, is_default, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
`

type InsertWorkspaceModelPolicyParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Phase       string      `db:"phase" json:"phase"`
	ModelID     pgtype.UUID `db:"model_id" json:"model_id"`
	IsDefault   bool        `db:"is_default" json:"is_default"`
}

func (q *Queries) InsertWorkspaceModelPolicy(ctx context.Context, arg InsertWorkspaceModelPolicyParams) error {
	_, err := q.db.Exec(ctx, insertWorkspaceModelPolicy,
		arg.WorkspaceID,
		arg.Phase,
		arg.ModelID,
		arg.IsDefault,
	)
	return err
}
