// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, slug, name, management_repo_id, branch_pattern, created_at, updated_at, slack_channel_id, organization_id
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ManagementRepoID,
		&i.BranchPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlackChannelID,
		&i.OrganizationID,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, slug, name, management_repo_id, branch_pattern, created_at, updated_at, slack_channel_id, organization_id
FROM workspaces
WHERE slug = $1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ManagementRepoID,
		&i.BranchPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlackChannelID,
		&i.OrganizationID,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, slug, name, management_repo_id, branch_pattern, created_at, updated_at, slack_channel_id, organization_id
FROM workspaces
ORDER BY updated_at DESC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ManagementRepoID,
			&i.BranchPattern,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SlackChannelID,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceByID = `-- name: UpdateWorkspaceByID :one
UPDATE workspaces
SET slug               = $2,
    name               = $3,
    management_repo_id = $4,
    branch_pattern     = $5,
    slack_channel_id   = $6,
    updated_at         = now()
WHERE id = $1
RETURNING id, slug, name, management_repo_id, branch_pattern, created_at, updated_at, slack_channel_id, organization_id
`

type UpdateWorkspaceByIDParams struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	Slug             string      `db:"slug" json:"slug"`
	Name             string      `db:"name" json:"name"`
	ManagementRepoID string      `db:"management_repo_id" json:"management_repo_id"`
	BranchPattern    *string     `db:"branch_pattern" json:"branch_pattern"`
	SlackChannelID   *string     `db:"slack_channel_id" json:"slack_channel_id"`
}

func (q *Queries) UpdateWorkspaceByID(ctx context.Context, arg UpdateWorkspaceByIDParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceByID,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.ManagementRepoID,
		arg.BranchPattern,
		arg.SlackChannelID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ManagementRepoID,
		&i.BranchPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlackChannelID,
		&i.OrganizationID,
	)
	return i, err
}

const upsertWorkspace = `-- name: UpsertWorkspace :one
INSERT INTO workspaces (id, organization_id, slug, name, management_repo_id, branch_pattern, slack_channel_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), now())
ON CONFLICT (slug) DO UPDATE SET
    name               = EXCLUDED.name,
    management_repo_id = EXCLUDED.management_repo_id,
    branch_pattern     = EXCLUDED.branch_pattern,
    slack_channel_id   = EXCLUDED.slack_channel_id,
    -- organization_id intentionally NOT updated on conflict
    updated_at         = now()
RETURNING id, slug, name, management_repo_id, branch_pattern, created_at, updated_at, slack_channel_id, organization_id
`

type UpsertWorkspaceParams struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	OrganizationID   pgtype.UUID `db:"organization_id" json:"organization_id"`
	Slug             string      `db:"slug" json:"slug"`
	Name             string      `db:"name" json:"name"`
	ManagementRepoID string      `db:"management_repo_id" json:"management_repo_id"`
	BranchPattern    *string     `db:"branch_pattern" json:"branch_pattern"`
	SlackChannelID   *string     `db:"slack_channel_id" json:"slack_channel_id"`
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, upsertWorkspace,
		arg.ID,
		arg.OrganizationID,
		arg.Slug,
		arg.Name,
		arg.ManagementRepoID,
		arg.BranchPattern,
		arg.SlackChannelID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ManagementRepoID,
		&i.BranchPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlackChannelID,
		&i.OrganizationID,
	)
	return i, err
}

const upsertWorkspaceByID = `-- name: UpsertWorkspaceByID :one
INSERT INTO workspaces (id, organization_id, slug, name, management_repo_id, branch_pattern, slack_channel_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), now())
ON CONFLICT (id) DO UPDATE SET
    slug               = EXCLUDED.slug,
    name               = EXCLUDED.name,
    management_repo_id = EXCLUDED.management_repo_id,
    branch_pattern     = EXCLUDED.branch_pattern,
    slack_channel_id   = EXCLUDED.slack_channel_id,
    -- organization_id intentionally NOT updated on conflict
    updated_at         = now()
RETURNING id, slug, name, management_repo_id, branch_pattern, created_at, updated_at, slack_channel_id, organization_id
`

type UpsertWorkspaceByIDParams struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	OrganizationID   pgtype.UUID `db:"organization_id" json:"organization_id"`
	Slug             string      `db:"slug" json:"slug"`
	Name             string      `db:"name" json:"name"`
	ManagementRepoID string      `db:"management_repo_id" json:"management_repo_id"`
	BranchPattern    *string     `db:"branch_pattern" json:"branch_pattern"`
	SlackChannelID   *string     `db:"slack_channel_id" json:"slack_channel_id"`
}

func (q *Queries) UpsertWorkspaceByID(ctx context.Context, arg UpsertWorkspaceByIDParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceByID,
		arg.ID,
		arg.OrganizationID,
		arg.Slug,
		arg.Name,
		arg.ManagementRepoID,
		arg.BranchPattern,
		arg.SlackChannelID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ManagementRepoID,
		&i.BranchPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SlackChannelID,
		&i.OrganizationID,
	)
	return i, err
}
