// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_repos.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWorkspaceReposNotIn = `-- name: DeleteWorkspaceReposNotIn :exec
DELETE FROM workspace_repos
WHERE workspace_id = $1
  AND repo_id != ALL($2::text[])
`

type DeleteWorkspaceReposNotInParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	RepoIds     []string    `db:"repo_ids" json:"repo_ids"`
}

func (q *Queries) DeleteWorkspaceReposNotIn(ctx context.Context, arg DeleteWorkspaceReposNotInParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceReposNotIn, arg.WorkspaceID, arg.RepoIds)
	return err
}

const listWorkspaceRepos = `-- name: ListWorkspaceRepos :many
SELECT id, workspace_id, repo_id, base_branch, repo_url, created_at, updated_at
FROM workspace_repos
WHERE workspace_id = $1
ORDER BY repo_id
`

type ListWorkspaceReposRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	RepoID      string             `db:"repo_id" json:"repo_id"`
	BaseBranch  *string            `db:"base_branch" json:"base_branch"`
	RepoUrl     *string            `db:"repo_url" json:"repo_url"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListWorkspaceRepos(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceReposRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceRepos, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceReposRow{}
	for rows.Next() {
		var i ListWorkspaceReposRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RepoID,
			&i.BaseBranch,
			&i.RepoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkspaceRepo = `-- name: UpsertWorkspaceRepo :one
INSERT INTO workspace_repos (workspace_id, repo_id, base_branch, repo_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
ON CONFLICT (workspace_id, repo_id) DO UPDATE SET
    base_branch = EXCLUDED.base_branch,
    repo_url    = EXCLUDED.repo_url,
    updated_at  = now()
RETURNING id, workspace_id, repo_id, base_branch, repo_url, created_at, updated_at
`

type UpsertWorkspaceRepoParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	RepoID      string      `db:"repo_id" json:"repo_id"`
	BaseBranch  *string     `db:"base_branch" json:"base_branch"`
	RepoUrl     *string     `db:"repo_url" json:"repo_url"`
}

type UpsertWorkspaceRepoRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	RepoID      string             `db:"repo_id" json:"repo_id"`
	BaseBranch  *string            `db:"base_branch" json:"base_branch"`
	RepoUrl     *string            `db:"repo_url" json:"repo_url"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertWorkspaceRepo(ctx context.Context, arg UpsertWorkspaceRepoParams) (UpsertWorkspaceRepoRow, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceRepo,
		arg.WorkspaceID,
		arg.RepoID,
		arg.BaseBranch,
		arg.RepoUrl,
	)
	var i UpsertWorkspaceRepoRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepoID,
		&i.BaseBranch,
		&i.RepoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
