// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGitHubSource = `-- name: GetGitHubSource :one
SELECT id, workspace_id, repo_url, repo_owner, repo_name, default_branch, created_at, updated_at
FROM workspace_github_sources
WHERE workspace_id = $1`

func (q *Queries) GetGitHubSource(ctx context.Context, workspaceID pgtype.UUID) (WorkspaceGitHubSource, error) {
	row := q.db.QueryRow(ctx, getGitHubSource, workspaceID)
	var i WorkspaceGitHubSource
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepoURL,
		&i.RepoOwner,
		&i.RepoName,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGitHubSource = `-- name: UpsertGitHubSource :one
INSERT INTO workspace_github_sources (
    workspace_id, repo_url, repo_owner, repo_name, default_branch, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, now(), now())
ON CONFLICT (workspace_id) DO UPDATE SET
    repo_url       = EXCLUDED.repo_url,
    repo_owner     = EXCLUDED.repo_owner,
    repo_name      = EXCLUDED.repo_name,
    default_branch = EXCLUDED.default_branch,
    updated_at     = now()
RETURNING id, workspace_id, repo_url, repo_owner, repo_name, default_branch, created_at, updated_at`

type UpsertGitHubSourceParams struct {
	WorkspaceID   pgtype.UUID
	RepoURL       string
	RepoOwner     string
	RepoName      string
	DefaultBranch *string
}

func (q *Queries) UpsertGitHubSource(ctx context.Context, arg UpsertGitHubSourceParams) (WorkspaceGitHubSource, error) {
	row := q.db.QueryRow(ctx, upsertGitHubSource,
		arg.WorkspaceID,
		arg.RepoURL,
		arg.RepoOwner,
		arg.RepoName,
		arg.DefaultBranch,
	)
	var i WorkspaceGitHubSource
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RepoURL,
		&i.RepoOwner,
		&i.RepoName,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
