// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_features.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWorkspaceFeaturesNotIn = `-- name: DeleteWorkspaceFeaturesNotIn :exec
DELETE FROM workspace_features
WHERE workspace_id = $1
  AND feature_name != ALL($2::text[])
  AND (owner IS NULL OR owner = '')
`

type DeleteWorkspaceFeaturesNotInParams struct {
	WorkspaceID  pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	FeatureNames []string    `db:"feature_names" json:"feature_names"`
}

func (q *Queries) DeleteWorkspaceFeaturesNotIn(ctx context.Context, arg DeleteWorkspaceFeaturesNotInParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceFeaturesNotIn, arg.WorkspaceID, arg.FeatureNames)
	return err
}

const getWorkspaceFeature = `-- name: GetWorkspaceFeature :one
SELECT id, workspace_id, title, feature_status, current_stage, next_action,
       stages, source_path, source_hash, created_at, updated_at,
       feature_name, feature_id, owner, init_pr_url, init_pr_merged
FROM workspace_features
WHERE workspace_id = $1 AND feature_id = $2
`

type GetWorkspaceFeatureParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	FeatureID   pgtype.UUID `db:"feature_id" json:"feature_id"`
}

func (q *Queries) GetWorkspaceFeature(ctx context.Context, arg GetWorkspaceFeatureParams) (WorkspaceFeature, error) {
	row := q.db.QueryRow(ctx, getWorkspaceFeature, arg.WorkspaceID, arg.FeatureID)
	var i WorkspaceFeature
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.FeatureStatus,
		&i.CurrentStage,
		&i.NextAction,
		&i.Stages,
		&i.SourcePath,
		&i.SourceHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeatureName,
		&i.FeatureID,
		&i.Owner,
		&i.InitPrUrl,
		&i.InitPrMerged,
	)
	return i, err
}

const listWorkspaceFeatures = `-- name: ListWorkspaceFeatures :many
SELECT id, workspace_id, title, feature_status, current_stage, next_action,
       stages, source_path, source_hash, created_at, updated_at,
       feature_name, feature_id, owner, init_pr_url, init_pr_merged
FROM workspace_features
WHERE workspace_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListWorkspaceFeatures(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceFeature, error) {
	rows, err := q.db.Query(ctx, listWorkspaceFeatures, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceFeature{}
	for rows.Next() {
		var i WorkspaceFeature
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.FeatureStatus,
			&i.CurrentStage,
			&i.NextAction,
			&i.Stages,
			&i.SourcePath,
			&i.SourceHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeatureName,
			&i.FeatureID,
			&i.Owner,
			&i.InitPrUrl,
			&i.InitPrMerged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkspaceFeature = `-- name: UpsertWorkspaceFeature :one
WITH feature_input AS (
    SELECT COALESCE(
        (SELECT id FROM workspace_features WHERE workspace_id = $1 AND feature_name = $2),
        gen_random_uuid()
    ) AS feature_uuid
)
INSERT INTO workspace_features (
    id, workspace_id, feature_id, feature_name, title, feature_status, current_stage, next_action,
    stages, source_path, source_hash, owner, created_at, updated_at
)
SELECT feature_uuid, $1, feature_uuid, $2, $3, $4, $5, $6, $7, $8, $9, $10, now(), now()
FROM feature_input
ON CONFLICT (workspace_id, feature_name) DO UPDATE SET
    title          = EXCLUDED.title,
    feature_status = CASE
        WHEN workspace_features.owner = 'go'
             AND workspace_features.feature_status IN ('in_implementation', 'in_handoff')
             AND EXCLUDED.feature_status NOT IN ('cancelled', 'done')
        THEN workspace_features.feature_status
        ELSE EXCLUDED.feature_status
    END,
    current_stage  = CASE
        WHEN workspace_features.owner = 'go'
             AND workspace_features.feature_status IN ('in_implementation', 'in_handoff')
             AND EXCLUDED.feature_status NOT IN ('cancelled', 'done')
        THEN workspace_features.current_stage
        ELSE EXCLUDED.current_stage
    END,
    next_action    = CASE
        WHEN workspace_features.owner = 'go'
             AND workspace_features.feature_status IN ('in_implementation', 'in_handoff')
             AND EXCLUDED.feature_status NOT IN ('cancelled', 'done')
        THEN workspace_features.next_action
        ELSE EXCLUDED.next_action
    END,
    stages         = EXCLUDED.stages,
    source_path    = EXCLUDED.source_path,
    source_hash    = EXCLUDED.source_hash,
    owner          = COALESCE(workspace_features.owner, EXCLUDED.owner),
    updated_at     = now()
RETURNING id, workspace_id, title, feature_status, current_stage, next_action,
          stages, source_path, source_hash, created_at, updated_at,
          feature_name, feature_id, owner, init_pr_url, init_pr_merged
`

type UpsertWorkspaceFeatureParams struct {
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	FeatureName   string      `db:"feature_name" json:"feature_name"`
	Title         string      `db:"title" json:"title"`
	FeatureStatus *string     `db:"feature_status" json:"feature_status"`
	CurrentStage  *string     `db:"current_stage" json:"current_stage"`
	NextAction    *string     `db:"next_action" json:"next_action"`
	Stages        []byte      `db:"stages" json:"stages"`
	SourcePath    *string     `db:"source_path" json:"source_path"`
	SourceHash    *string     `db:"source_hash" json:"source_hash"`
	Owner         *string     `db:"owner" json:"owner"`
}

func (q *Queries) UpsertWorkspaceFeature(ctx context.Context, arg UpsertWorkspaceFeatureParams) (WorkspaceFeature, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceFeature,
		arg.WorkspaceID,
		arg.FeatureName,
		arg.Title,
		arg.FeatureStatus,
		arg.CurrentStage,
		arg.NextAction,
		arg.Stages,
		arg.SourcePath,
		arg.SourceHash,
		arg.Owner,
	)
	var i WorkspaceFeature
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.FeatureStatus,
		&i.CurrentStage,
		&i.NextAction,
		&i.Stages,
		&i.SourcePath,
		&i.SourceHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeatureName,
		&i.FeatureID,
		&i.Owner,
		&i.InitPrUrl,
		&i.InitPrMerged,
	)
	return i, err
}
