// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_sync_runs.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestSyncRun = `-- name: GetLatestSyncRun :one
SELECT id, workspace_id, trigger, branch, mode, status,
       commit_sha, changed_paths, started_at, finished_at, error_code, error_message, metadata,
       feature_id, task_id
FROM workspace_sync_runs
WHERE workspace_id = $1
ORDER BY finished_at DESC NULLS LAST
LIMIT 1
`

func (q *Queries) GetLatestSyncRun(ctx context.Context, workspaceID pgtype.UUID) (WorkspaceSyncRun, error) {
	row := q.db.QueryRow(ctx, getLatestSyncRun, workspaceID)
	var i WorkspaceSyncRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Trigger,
		&i.Branch,
		&i.Mode,
		&i.Status,
		&i.CommitSha,
		&i.ChangedPaths,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.FeatureID,
		&i.TaskID,
	)
	return i, err
}

const insertSyncRun = `-- name: InsertSyncRun :one
INSERT INTO workspace_sync_runs (
    workspace_id, trigger, branch, feature_id, task_id, mode, status,
    commit_sha, changed_paths, started_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
RETURNING id, workspace_id, trigger, branch, mode, status,
          commit_sha, changed_paths, started_at, finished_at, error_code, error_message, metadata,
          feature_id, task_id
`

type InsertSyncRunParams struct {
	WorkspaceID  pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Trigger      string      `db:"trigger" json:"trigger"`
	Branch       *string     `db:"branch" json:"branch"`
	FeatureID    pgtype.UUID `db:"feature_id" json:"feature_id"`
	TaskID       pgtype.UUID `db:"task_id" json:"task_id"`
	Mode         string      `db:"mode" json:"mode"`
	Status       string      `db:"status" json:"status"`
	CommitSha    *string     `db:"commit_sha" json:"commit_sha"`
	ChangedPaths []byte      `db:"changed_paths" json:"changed_paths"`
}

func (q *Queries) InsertSyncRun(ctx context.Context, arg InsertSyncRunParams) (WorkspaceSyncRun, error) {
	row := q.db.QueryRow(ctx, insertSyncRun,
		arg.WorkspaceID,
		arg.Trigger,
		arg.Branch,
		arg.FeatureID,
		arg.TaskID,
		arg.Mode,
		arg.Status,
		arg.CommitSha,
		arg.ChangedPaths,
	)
	var i WorkspaceSyncRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Trigger,
		&i.Branch,
		&i.Mode,
		&i.Status,
		&i.CommitSha,
		&i.ChangedPaths,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.FeatureID,
		&i.TaskID,
	)
	return i, err
}

const listLatestSyncRunsPerWorkspace = `-- name: ListLatestSyncRunsPerWorkspace :many
SELECT DISTINCT ON (workspace_id) id, workspace_id, trigger, branch, mode, status,
       commit_sha, changed_paths, started_at, finished_at, error_code, error_message, metadata,
       feature_id, task_id
FROM workspace_sync_runs
ORDER BY workspace_id, finished_at DESC NULLS LAST
`

func (q *Queries) ListLatestSyncRunsPerWorkspace(ctx context.Context) ([]WorkspaceSyncRun, error) {
	rows, err := q.db.Query(ctx, listLatestSyncRunsPerWorkspace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceSyncRun{}
	for rows.Next() {
		var i WorkspaceSyncRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Trigger,
			&i.Branch,
			&i.Mode,
			&i.Status,
			&i.CommitSha,
			&i.ChangedPaths,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Metadata,
			&i.FeatureID,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSyncRunFailed = `-- name: UpdateSyncRunFailed :one
UPDATE workspace_sync_runs SET
    status        = 'failed',
    error_code    = $2,
    error_message = $3,
    finished_at   = now()
WHERE id = $1
RETURNING id, workspace_id, trigger, branch, mode, status,
          commit_sha, changed_paths, started_at, finished_at, error_code, error_message, metadata,
          feature_id, task_id
`

type UpdateSyncRunFailedParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	ErrorCode    *string     `db:"error_code" json:"error_code"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
}

func (q *Queries) UpdateSyncRunFailed(ctx context.Context, arg UpdateSyncRunFailedParams) (WorkspaceSyncRun, error) {
	row := q.db.QueryRow(ctx, updateSyncRunFailed, arg.ID, arg.ErrorCode, arg.ErrorMessage)
	var i WorkspaceSyncRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Trigger,
		&i.Branch,
		&i.Mode,
		&i.Status,
		&i.CommitSha,
		&i.ChangedPaths,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.FeatureID,
		&i.TaskID,
	)
	return i, err
}

const updateSyncRunSuccess = `-- name: UpdateSyncRunSuccess :one
UPDATE workspace_sync_runs SET
    status      = 'success',
    commit_sha  = $2,
    finished_at = now()
WHERE id = $1
RETURNING id, workspace_id, trigger, branch, mode, status,
          commit_sha, changed_paths, started_at, finished_at, error_code, error_message, metadata,
          feature_id, task_id
`

type UpdateSyncRunSuccessParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	CommitSha *string     `db:"commit_sha" json:"commit_sha"`
}

func (q *Queries) UpdateSyncRunSuccess(ctx context.Context, arg UpdateSyncRunSuccessParams) (WorkspaceSyncRun, error) {
	row := q.db.QueryRow(ctx, updateSyncRunSuccess, arg.ID, arg.CommitSha)
	var i WorkspaceSyncRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Trigger,
		&i.Branch,
		&i.Mode,
		&i.Status,
		&i.CommitSha,
		&i.ChangedPaths,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.FeatureID,
		&i.TaskID,
	)
	return i, err
}
