// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listFeatureDocuments = `-- name: ListFeatureDocuments :many
SELECT id, workspace_id, feature_id, feature_name, document_type, source_path, url, created_at, updated_at
FROM workspace_feature_documents
WHERE workspace_id = $1 AND feature_id = $2
ORDER BY document_type`

type ListFeatureDocumentsParams struct {
	WorkspaceID pgtype.UUID
	FeatureID   pgtype.UUID
}

func (q *Queries) ListFeatureDocuments(ctx context.Context, arg ListFeatureDocumentsParams) ([]WorkspaceFeatureDocument, error) {
	rows, err := q.db.Query(ctx, listFeatureDocuments, arg.WorkspaceID, arg.FeatureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceFeatureDocument
	for rows.Next() {
		var i WorkspaceFeatureDocument
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FeatureID,
			&i.FeatureName,
			&i.DocumentType,
			&i.SourcePath,
			&i.URL,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceFeatureDocuments = `-- name: ListWorkspaceFeatureDocuments :many
SELECT id, workspace_id, feature_id, feature_name, document_type, source_path, url, created_at, updated_at
FROM workspace_feature_documents
WHERE workspace_id = $1
ORDER BY feature_name, document_type`

func (q *Queries) ListWorkspaceFeatureDocuments(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceFeatureDocument, error) {
	rows, err := q.db.Query(ctx, listWorkspaceFeatureDocuments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceFeatureDocument
	for rows.Next() {
		var i WorkspaceFeatureDocument
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.FeatureID,
			&i.FeatureName,
			&i.DocumentType,
			&i.SourcePath,
			&i.URL,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeatureDocument = `-- name: UpsertFeatureDocument :one
INSERT INTO workspace_feature_documents (
    workspace_id, feature_id, feature_name, document_type, source_path, url, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, now(), now())
ON CONFLICT (workspace_id, feature_id, document_type) DO UPDATE SET
    feature_name  = EXCLUDED.feature_name,
    source_path   = EXCLUDED.source_path,
    url           = EXCLUDED.url,
    updated_at    = now()
RETURNING id, workspace_id, feature_id, feature_name, document_type, source_path, url, created_at, updated_at`

type UpsertFeatureDocumentParams struct {
	WorkspaceID  pgtype.UUID
	FeatureID    pgtype.UUID
	FeatureName  string
	DocumentType string
	SourcePath   string
	URL          *string
}

func (q *Queries) UpsertFeatureDocument(ctx context.Context, arg UpsertFeatureDocumentParams) (WorkspaceFeatureDocument, error) {
	row := q.db.QueryRow(ctx, upsertFeatureDocument,
		arg.WorkspaceID,
		arg.FeatureID,
		arg.FeatureName,
		arg.DocumentType,
		arg.SourcePath,
		arg.URL,
	)
	var i WorkspaceFeatureDocument
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FeatureID,
		&i.FeatureName,
		&i.DocumentType,
		&i.SourcePath,
		&i.URL,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFeatureDocumentsNotIn = `-- name: DeleteFeatureDocumentsNotIn :exec
DELETE FROM workspace_feature_documents
WHERE workspace_id = $1
  AND feature_id = $2
  AND document_type != ALL($3::text[])`

type DeleteFeatureDocumentsNotInParams struct {
	WorkspaceID   pgtype.UUID
	FeatureID     pgtype.UUID
	DocumentTypes []string
}

func (q *Queries) DeleteFeatureDocumentsNotIn(ctx context.Context, arg DeleteFeatureDocumentsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteFeatureDocumentsNotIn, arg.WorkspaceID, arg.FeatureID, arg.DocumentTypes)
	return err
}

const deleteAllFeatureDocuments = `-- name: DeleteAllFeatureDocuments :exec
DELETE FROM workspace_feature_documents
WHERE workspace_id = $1 AND feature_id = $2`

type DeleteAllFeatureDocumentsParams struct {
	WorkspaceID pgtype.UUID
	FeatureID   pgtype.UUID
}

func (q *Queries) DeleteAllFeatureDocuments(ctx context.Context, arg DeleteAllFeatureDocumentsParams) error {
	_, err := q.db.Exec(ctx, deleteAllFeatureDocuments, arg.WorkspaceID, arg.FeatureID)
	return err
}
