// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActivityEvents = `-- name: ListActivityEvents :many
SELECT id, workspace_id, scope_type, feature_id, task_id, action, actor,
       occurred_at, note, sequence, raw_event, created_at
FROM workspace_activity_events
WHERE workspace_id = $1
ORDER BY occurred_at DESC, sequence DESC`

func (q *Queries) ListActivityEvents(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceActivityEvent, error) {
	rows, err := q.db.Query(ctx, listActivityEvents, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceActivityEvent
	for rows.Next() {
		var i WorkspaceActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ScopeType,
			&i.FeatureID,
			&i.TaskID,
			&i.Action,
			&i.Actor,
			&i.OccurredAt,
			&i.Note,
			&i.Sequence,
			&i.RawEvent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureActivityEvents = `-- name: ListFeatureActivityEvents :many
SELECT id, workspace_id, scope_type, feature_id, task_id, action, actor,
       occurred_at, note, sequence, raw_event, created_at
FROM workspace_activity_events
WHERE workspace_id = $1 AND feature_id::text = $2
ORDER BY occurred_at DESC, sequence DESC`

type ListFeatureActivityEventsParams struct {
	WorkspaceID pgtype.UUID
	FeatureID   string
}

func (q *Queries) ListFeatureActivityEvents(ctx context.Context, arg ListFeatureActivityEventsParams) ([]WorkspaceActivityEvent, error) {
	rows, err := q.db.Query(ctx, listFeatureActivityEvents, arg.WorkspaceID, arg.FeatureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceActivityEvent
	for rows.Next() {
		var i WorkspaceActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ScopeType,
			&i.FeatureID,
			&i.TaskID,
			&i.Action,
			&i.Actor,
			&i.OccurredAt,
			&i.Note,
			&i.Sequence,
			&i.RawEvent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskActivityEvents = `-- name: ListTaskActivityEvents :many
SELECT id, workspace_id, scope_type, feature_id, task_id, action, actor,
       occurred_at, note, sequence, raw_event, created_at
FROM workspace_activity_events
WHERE workspace_id = $1 AND feature_id::text = $2 AND task_id::text = $3
ORDER BY sequence`

type ListTaskActivityEventsParams struct {
	WorkspaceID pgtype.UUID
	FeatureID   string
	TaskID      string
}

func (q *Queries) ListTaskActivityEvents(ctx context.Context, arg ListTaskActivityEventsParams) ([]WorkspaceActivityEvent, error) {
	rows, err := q.db.Query(ctx, listTaskActivityEvents, arg.WorkspaceID, arg.FeatureID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceActivityEvent
	for rows.Next() {
		var i WorkspaceActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ScopeType,
			&i.FeatureID,
			&i.TaskID,
			&i.Action,
			&i.Actor,
			&i.OccurredAt,
			&i.Note,
			&i.Sequence,
			&i.RawEvent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// UpsertFeatureActivityEventParams parameters for feature-level activity (task_id IS NULL).
// Targets partial index: WHERE feature_id IS NOT NULL AND task_id IS NULL.
const upsertFeatureActivityEvent = `-- name: UpsertFeatureActivityEvent :one
INSERT INTO workspace_activity_events (
    workspace_id, scope_type, feature_id, feature_name, task_id, action, actor,
    occurred_at, note, sequence, raw_event, created_at
)
VALUES ($1, $2, $3, $4, NULL, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (workspace_id, feature_id, sequence)
    WHERE feature_id IS NOT NULL AND task_id IS NULL
DO UPDATE SET
    scope_type   = EXCLUDED.scope_type,
    feature_name = EXCLUDED.feature_name,
    action       = EXCLUDED.action,
    actor       = EXCLUDED.actor,
    occurred_at = EXCLUDED.occurred_at,
    note        = EXCLUDED.note,
    raw_event   = EXCLUDED.raw_event
RETURNING id, workspace_id, scope_type, feature_id, task_id, action, actor,
          occurred_at, note, sequence, raw_event, created_at`

type UpsertFeatureActivityEventParams struct {
	WorkspaceID pgtype.UUID
	ScopeType   string
	FeatureID   pgtype.UUID
	FeatureName string
	Action      *string
	Actor       *string
	OccurredAt  *string
	Note        *string
	Sequence    int32
	RawEvent    json.RawMessage
}

func (q *Queries) UpsertFeatureActivityEvent(ctx context.Context, arg UpsertFeatureActivityEventParams) (WorkspaceActivityEvent, error) {
	row := q.db.QueryRow(ctx, upsertFeatureActivityEvent,
		arg.WorkspaceID,
		arg.ScopeType,
		arg.FeatureID,
		arg.FeatureName,
		arg.Action,
		arg.Actor,
		arg.OccurredAt,
		arg.Note,
		arg.Sequence,
		arg.RawEvent,
	)
	var i WorkspaceActivityEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.FeatureID,
		&i.TaskID,
		&i.Action,
		&i.Actor,
		&i.OccurredAt,
		&i.Note,
		&i.Sequence,
		&i.RawEvent,
		&i.CreatedAt,
	)
	return i, err
}

// UpsertTaskActivityEventParams parameters for task-level activity (both feature_id and task_id non-null).
// Targets partial index: WHERE feature_id IS NOT NULL AND task_id IS NOT NULL.
const upsertTaskActivityEvent = `-- name: UpsertTaskActivityEvent :one
INSERT INTO workspace_activity_events (
    workspace_id, scope_type, feature_id, feature_name, task_id, task_name, action, actor,
    occurred_at, note, sequence, raw_event, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now())
ON CONFLICT (workspace_id, feature_id, task_id, sequence)
    WHERE feature_id IS NOT NULL AND task_id IS NOT NULL
DO UPDATE SET
    scope_type   = EXCLUDED.scope_type,
    feature_name = EXCLUDED.feature_name,
    task_name    = EXCLUDED.task_name,
    action       = EXCLUDED.action,
    actor       = EXCLUDED.actor,
    occurred_at = EXCLUDED.occurred_at,
    note        = EXCLUDED.note,
    raw_event   = EXCLUDED.raw_event
RETURNING id, workspace_id, scope_type, feature_id, task_id, action, actor,
          occurred_at, note, sequence, raw_event, created_at`

type UpsertTaskActivityEventParams struct {
	WorkspaceID pgtype.UUID
	ScopeType   string
	FeatureID   pgtype.UUID
	FeatureName string
	TaskID      pgtype.UUID
	TaskName    string
	Action      *string
	Actor       *string
	OccurredAt  *string
	Note        *string
	Sequence    int32
	RawEvent    json.RawMessage
}

func (q *Queries) UpsertTaskActivityEvent(ctx context.Context, arg UpsertTaskActivityEventParams) (WorkspaceActivityEvent, error) {
	row := q.db.QueryRow(ctx, upsertTaskActivityEvent,
		arg.WorkspaceID,
		arg.ScopeType,
		arg.FeatureID,
		arg.FeatureName,
		arg.TaskID,
		arg.TaskName,
		arg.Action,
		arg.Actor,
		arg.OccurredAt,
		arg.Note,
		arg.Sequence,
		arg.RawEvent,
	)
	var i WorkspaceActivityEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ScopeType,
		&i.FeatureID,
		&i.TaskID,
		&i.Action,
		&i.Actor,
		&i.OccurredAt,
		&i.Note,
		&i.Sequence,
		&i.RawEvent,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllFeatureActivityEvents = `-- name: DeleteAllFeatureActivityEvents :exec
DELETE FROM workspace_activity_events
WHERE workspace_id = $1 AND feature_id::text = $2`

type DeleteAllFeatureActivityEventsParams struct {
	WorkspaceID pgtype.UUID
	FeatureID   string
}

func (q *Queries) DeleteAllFeatureActivityEvents(ctx context.Context, arg DeleteAllFeatureActivityEventsParams) error {
	_, err := q.db.Exec(ctx, deleteAllFeatureActivityEvents, arg.WorkspaceID, arg.FeatureID)
	return err
}
