// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_tasks.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllFeatureTasks = `-- name: DeleteAllFeatureTasks :exec
DELETE FROM workspace_tasks
WHERE workspace_id = $1 AND feature_id = $2
  AND (owner IS NULL OR owner = '')
`

type DeleteAllFeatureTasksParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	FeatureID   pgtype.UUID `db:"feature_id" json:"feature_id"`
}

func (q *Queries) DeleteAllFeatureTasks(ctx context.Context, arg DeleteAllFeatureTasksParams) error {
	_, err := q.db.Exec(ctx, deleteAllFeatureTasks, arg.WorkspaceID, arg.FeatureID)
	return err
}

const deleteFeatureTasksNotIn = `-- name: DeleteFeatureTasksNotIn :exec
DELETE FROM workspace_tasks
WHERE workspace_id = $1
  AND feature_id = $2
  AND task_name != ALL($3::text[])
  AND (owner IS NULL OR owner = '')
`

type DeleteFeatureTasksNotInParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	FeatureID   pgtype.UUID `db:"feature_id" json:"feature_id"`
	TaskNames   []string    `db:"task_names" json:"task_names"`
}

func (q *Queries) DeleteFeatureTasksNotIn(ctx context.Context, arg DeleteFeatureTasksNotInParams) error {
	_, err := q.db.Exec(ctx, deleteFeatureTasksNotIn, arg.WorkspaceID, arg.FeatureID, arg.TaskNames)
	return err
}

const getWorkspaceTask = `-- name: GetWorkspaceTask :one
SELECT id, workspace_id, title, repo, status, depends_on,
       blocked_reason, branch, execution, pr, workspace_pr, source_path, source_hash,
       created_at, updated_at, feature_name, feature_id, task_name, task_id, owner
FROM workspace_tasks
WHERE workspace_id = $1 AND feature_id = $2 AND task_id = $3
`

type GetWorkspaceTaskParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	FeatureID   pgtype.UUID `db:"feature_id" json:"feature_id"`
	TaskID      pgtype.UUID `db:"task_id" json:"task_id"`
}

func (q *Queries) GetWorkspaceTask(ctx context.Context, arg GetWorkspaceTaskParams) (WorkspaceTask, error) {
	row := q.db.QueryRow(ctx, getWorkspaceTask, arg.WorkspaceID, arg.FeatureID, arg.TaskID)
	var i WorkspaceTask
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Repo,
		&i.Status,
		&i.DependsOn,
		&i.BlockedReason,
		&i.Branch,
		&i.Execution,
		&i.Pr,
		&i.WorkspacePr,
		&i.SourcePath,
		&i.SourceHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeatureName,
		&i.FeatureID,
		&i.TaskName,
		&i.TaskID,
		&i.Owner,
	)
	return i, err
}

const listFeatureTasks = `-- name: ListFeatureTasks :many
SELECT id, workspace_id, title, repo, status, depends_on,
       blocked_reason, branch, execution, pr, workspace_pr, source_path, source_hash,
       created_at, updated_at, feature_name, feature_id, task_name, task_id, owner
FROM workspace_tasks
WHERE workspace_id = $1 AND feature_id = $2
ORDER BY CASE WHEN task_name::text ~ '^T[0-9]+$' THEN substring(task_name::text from 2)::int END ASC NULLS LAST, task_name::text ASC
`

type ListFeatureTasksParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	FeatureID   pgtype.UUID `db:"feature_id" json:"feature_id"`
}

func (q *Queries) ListFeatureTasks(ctx context.Context, arg ListFeatureTasksParams) ([]WorkspaceTask, error) {
	rows, err := q.db.Query(ctx, listFeatureTasks, arg.WorkspaceID, arg.FeatureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceTask{}
	for rows.Next() {
		var i WorkspaceTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Repo,
			&i.Status,
			&i.DependsOn,
			&i.BlockedReason,
			&i.Branch,
			&i.Execution,
			&i.Pr,
			&i.WorkspacePr,
			&i.SourcePath,
			&i.SourceHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeatureName,
			&i.FeatureID,
			&i.TaskName,
			&i.TaskID,
			&i.Owner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceTasks = `-- name: ListWorkspaceTasks :many
SELECT id, workspace_id, title, repo, status, depends_on,
       blocked_reason, branch, execution, pr, workspace_pr, source_path, source_hash,
       created_at, updated_at, feature_name, feature_id, task_name, task_id, owner
FROM workspace_tasks
WHERE workspace_id = $1
ORDER BY feature_name, CASE WHEN task_name::text ~ '^T[0-9]+$' THEN substring(task_name::text from 2)::int END ASC NULLS LAST, task_name::text ASC
`

func (q *Queries) ListWorkspaceTasks(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceTask, error) {
	rows, err := q.db.Query(ctx, listWorkspaceTasks, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceTask{}
	for rows.Next() {
		var i WorkspaceTask
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Repo,
			&i.Status,
			&i.DependsOn,
			&i.BlockedReason,
			&i.Branch,
			&i.Execution,
			&i.Pr,
			&i.WorkspacePr,
			&i.SourcePath,
			&i.SourceHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeatureName,
			&i.FeatureID,
			&i.TaskName,
			&i.TaskID,
			&i.Owner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkspaceTask = `-- name: UpsertWorkspaceTask :one
WITH task_input AS (
    SELECT COALESCE(
        (SELECT id FROM workspace_tasks WHERE workspace_id = $1 AND feature_id = $2 AND task_name = $4),
        gen_random_uuid()
    ) AS task_uuid
)
INSERT INTO workspace_tasks (
    id, workspace_id, feature_id, feature_name, task_id, task_name, title, repo, status, depends_on,
    blocked_reason, branch, execution, pr, workspace_pr, source_path, source_hash,
    created_at, updated_at
)
SELECT task_uuid, $1, $2, $3, task_uuid, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, now(), now()
FROM task_input
ON CONFLICT (workspace_id, feature_id, task_name) DO UPDATE SET
    feature_name   = EXCLUDED.feature_name,
    title          = EXCLUDED.title,
    repo           = EXCLUDED.repo,
    status         = EXCLUDED.status,
    depends_on     = EXCLUDED.depends_on,
    blocked_reason = EXCLUDED.blocked_reason,
    branch         = EXCLUDED.branch,
    execution      = EXCLUDED.execution,
    pr             = EXCLUDED.pr,
    workspace_pr   = EXCLUDED.workspace_pr,
    source_path    = EXCLUDED.source_path,
    source_hash    = EXCLUDED.source_hash,
    owner          = COALESCE(workspace_tasks.owner, EXCLUDED.owner),
    updated_at     = now()
RETURNING id, workspace_id, title, repo, status, depends_on,
          blocked_reason, branch, execution, pr, workspace_pr, source_path, source_hash,
          created_at, updated_at, feature_name, feature_id, task_name, task_id, owner
`

type UpsertWorkspaceTaskParams struct {
	WorkspaceID   pgtype.UUID     `db:"workspace_id" json:"workspace_id"`
	FeatureID     pgtype.UUID     `db:"feature_id" json:"feature_id"`
	FeatureName   string          `db:"feature_name" json:"feature_name"`
	TaskName      string          `db:"task_name" json:"task_name"`
	Title         string          `db:"title" json:"title"`
	Repo          *string         `db:"repo" json:"repo"`
	Status        *string         `db:"status" json:"status"`
	DependsOn     json.RawMessage `db:"depends_on" json:"depends_on"`
	BlockedReason *string         `db:"blocked_reason" json:"blocked_reason"`
	Branch        *string         `db:"branch" json:"branch"`
	Execution     []byte          `db:"execution" json:"execution"`
	Pr            []byte          `db:"pr" json:"pr"`
	WorkspacePr   []byte          `db:"workspace_pr" json:"workspace_pr"`
	SourcePath    *string         `db:"source_path" json:"source_path"`
	SourceHash    *string         `db:"source_hash" json:"source_hash"`
}

func (q *Queries) UpsertWorkspaceTask(ctx context.Context, arg UpsertWorkspaceTaskParams) (WorkspaceTask, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceTask,
		arg.WorkspaceID,
		arg.FeatureID,
		arg.FeatureName,
		arg.TaskName,
		arg.Title,
		arg.Repo,
		arg.Status,
		arg.DependsOn,
		arg.BlockedReason,
		arg.Branch,
		arg.Execution,
		arg.Pr,
		arg.WorkspacePr,
		arg.SourcePath,
		arg.SourceHash,
	)
	var i WorkspaceTask
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Repo,
		&i.Status,
		&i.DependsOn,
		&i.BlockedReason,
		&i.Branch,
		&i.Execution,
		&i.Pr,
		&i.WorkspacePr,
		&i.SourcePath,
		&i.SourceHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeatureName,
		&i.FeatureID,
		&i.TaskName,
		&i.TaskID,
		&i.Owner,
	)
	return i, err
}
