// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, slug, name, management_repo_id, branch_pattern, created_at, updated_at
FROM workspaces
ORDER BY updated_at DESC`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ManagementRepoID,
			&i.BranchPattern,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, slug, name, management_repo_id, branch_pattern, created_at, updated_at
FROM workspaces
WHERE id = $1`

func (q *Queries) GetWorkspace(ctx context.Context, id pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ManagementRepoID,
		&i.BranchPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, slug, name, management_repo_id, branch_pattern, created_at, updated_at
FROM workspaces
WHERE slug = $1`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ManagementRepoID,
		&i.BranchPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkspace = `-- name: UpsertWorkspace :one
INSERT INTO workspaces (id, slug, name, management_repo_id, branch_pattern, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
ON CONFLICT (slug) DO UPDATE SET
    name               = EXCLUDED.name,
    management_repo_id = EXCLUDED.management_repo_id,
    branch_pattern     = EXCLUDED.branch_pattern,
    updated_at         = now()
RETURNING id, slug, name, management_repo_id, branch_pattern, created_at, updated_at`

type UpsertWorkspaceParams struct {
	ID               pgtype.UUID
	Slug             string
	Name             string
	ManagementRepoID string
	BranchPattern    *string
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, upsertWorkspace,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.ManagementRepoID,
		arg.BranchPattern,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ManagementRepoID,
		&i.BranchPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkspaceByID = `-- name: UpsertWorkspaceByID :one
INSERT INTO workspaces (id, slug, name, management_repo_id, branch_pattern, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
ON CONFLICT (id) DO UPDATE SET
    slug               = EXCLUDED.slug,
    name               = EXCLUDED.name,
    management_repo_id = EXCLUDED.management_repo_id,
    branch_pattern     = EXCLUDED.branch_pattern,
    updated_at         = now()
RETURNING id, slug, name, management_repo_id, branch_pattern, created_at, updated_at`

type UpsertWorkspaceByIDParams struct {
	ID               pgtype.UUID
	Slug             string
	Name             string
	ManagementRepoID string
	BranchPattern    *string
}

func (q *Queries) UpsertWorkspaceByID(ctx context.Context, arg UpsertWorkspaceByIDParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceByID,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.ManagementRepoID,
		arg.BranchPattern,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ManagementRepoID,
		&i.BranchPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspaceByID = `-- name: UpdateWorkspaceByID :one
UPDATE workspaces
SET slug               = $2,
    name               = $3,
    management_repo_id = $4,
    branch_pattern     = $5,
    updated_at         = now()
WHERE id = $1
RETURNING id, slug, name, management_repo_id, branch_pattern, created_at, updated_at`

type UpdateWorkspaceByIDParams struct {
	ID               pgtype.UUID
	Slug             string
	Name             string
	ManagementRepoID string
	BranchPattern    *string
}

func (q *Queries) UpdateWorkspaceByID(ctx context.Context, arg UpdateWorkspaceByIDParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceByID,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.ManagementRepoID,
		arg.BranchPattern,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.ManagementRepoID,
		&i.BranchPattern,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
