run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - copyloopvar
    - gocritic
    - noctx

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    shadow: true
  goimports:
    local-prefixes: github.com/tiendv89/workspace-github-adapter

issues:
  exclude-use-default: false
  max-same-issues: 0
